### ISSUE TITLE
Get more structured metadata for episodes

### ISSUE THREAD

**Issue by noman-land** [noman-land/transcript.fish#70]
- [x] ~Hosts of every episode including guests~ (#119) 
- [x] ~Make hosts table~ (#119)
- [x] ~Venue info~ (#119)
- [x] ~if live or not~ (#119)
- [x] ~if compilation~ (#119)
- [ ] ~The four facts~ (later)
